# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18J12SXtOzLe05bMEV2VLsQcmCy3x-c_b
"""

import pandas as pd
import joblib
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Load dataset (Replace this with your actual dataset)
data = pd.read_csv("spam.csv", encoding="latin-1")  # Change the file name if different

# Select only necessary columns
data = data[['v1', 'v2']]
data.columns = ['label', 'message']

# Convert labels to binary (spam = 1, ham = 0)
data['label'] = data['label'].map({'ham': 0, 'spam': 1})

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(data['message'], data['label'], test_size=0.2, random_state=42)

# Create a pipeline with CountVectorizer and MultinomialNB
pipeline = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', MultinomialNB())
])

# Train the model
pipeline.fit(X_train, y_train)

# Save the trained model and vectorizer
joblib.dump(pipeline, "spam_model.pkl")

print("Model trained and saved as spam_model.pkl")